id: I9454009C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:06:09+00:00'
last_modified: '2022-06-08T17:58:11.113031+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W15269
  title: ཀུན་དགའ་རྣམ་རྒྱལ་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    860D:
      image_group_id: I1KG5126
      title: Volume 1 of kun dga' rnam rgyal gyi rnam thar
      total_pages: 234
      order: 1
      base_file: 860D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
