id: P008035
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W15269
  title: ཀུན་དགའ་རྣམ་རྒྱལ་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    04810661f1ab4cdbae2045a646b7da27:
      image_group_id: I1KG5126
      title: Volume 1 of kun dga' rnam rgyal gyi rnam thar
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
